// File generated from our OpenAPI spec by Stainless.

package com.tryfinch.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.tryfinch.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BenefitsSupportTest {

    @Test
    fun create() {
        val benefitsSupport =
            BenefitsSupport.builder()
                .commuter(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .customPostTax(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .customPreTax(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .fsaDependentCare(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .fsaMedical(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .hsaPost(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .hsaPre(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .s125Dental(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .s125Medical(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .s125Vision(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .simple(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .simpleIra(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(benefitsSupport.commuter())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.customPostTax())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.customPreTax())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.fsaDependentCare())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.fsaMedical())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.hsaPost())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.hsaPre())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.s125Dental())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.s125Medical())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.s125Vision())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.simple())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(benefitsSupport.simpleIra())
            .isEqualTo(
                BenefitFeaturesAndOperations.builder()
                    .supportedFeatures(
                        SupportedBenefit.builder()
                            .annualMaximum(true)
                            .catchUp(true)
                            .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                            .description("description")
                            .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                            .addFrequency(BenefitFrequency.ONE_TIME)
                            .addHsaContributionLimit(
                                SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                            )
                            .build()
                    )
                    .supportedOperations(
                        SupportPerBenefitType.builder()
                            .companyBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .individualBenefits(
                                OperationSupportMatrix.builder()
                                    .create(OperationSupport.SUPPORTED)
                                    .delete(OperationSupport.SUPPORTED)
                                    .read(OperationSupport.SUPPORTED)
                                    .update(OperationSupport.SUPPORTED)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val benefitsSupport =
            BenefitsSupport.builder()
                .commuter(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .customPostTax(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .customPreTax(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .fsaDependentCare(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .fsaMedical(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .hsaPost(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .hsaPre(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .s125Dental(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .s125Medical(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .s125Vision(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .simple(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .simpleIra(
                    BenefitFeaturesAndOperations.builder()
                        .supportedFeatures(
                            SupportedBenefit.builder()
                                .annualMaximum(true)
                                .catchUp(true)
                                .addCompanyContribution(SupportedBenefit.CompanyContribution.FIXED)
                                .description("description")
                                .addEmployeeDeduction(SupportedBenefit.EmployeeDeduction.FIXED)
                                .addFrequency(BenefitFrequency.ONE_TIME)
                                .addHsaContributionLimit(
                                    SupportedBenefit.HsaContributionLimit.INDIVIDUAL
                                )
                                .build()
                        )
                        .supportedOperations(
                            SupportPerBenefitType.builder()
                                .companyBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .individualBenefits(
                                    OperationSupportMatrix.builder()
                                        .create(OperationSupport.SUPPORTED)
                                        .delete(OperationSupport.SUPPORTED)
                                        .read(OperationSupport.SUPPORTED)
                                        .update(OperationSupport.SUPPORTED)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedBenefitsSupport =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(benefitsSupport),
                jacksonTypeRef<BenefitsSupport>(),
            )

        assertThat(roundtrippedBenefitsSupport).isEqualTo(benefitsSupport)
    }
}
